# Generated by Django 3.1.2 on 2020-10-16 11:20

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0002_auto_20201016_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
    ]
